version: "3.8"
services:
  ibfflood:
    build:
      context: .
    image: ibf-drought-pipeline
    ports:
      - "587:587"
    env_file:
      - secrets.env
    volumes: 
      - ./pipeline:/home/fbf
    command: run-drought-model